
// lay ra toan bo san pham
const getAllProducts = async () => {
    return data;
};

module.exports = { getAllProducts };

var data = [{
    "_id": 4,
    "name": "Tres-Zap",
    "price": 573,
    "quantity": 1,
    "image": "https://cdn.tgdd.vn/Products/Images/42/251192/iphone-14-pro-den-1-1.jpg",
    "category": 10
  }, {
    "_id": 15,
    "name": "Tampflex",
    "price": 971,
    "quantity": 4,
    "image": "https://cdn.tgdd.vn/Products/Images/42/251192/iphone-14-pro-den-1-1.jpg",
    "category": 7
  }, {
    "_id": 8,
    "name": "Subin",
    "price": 923,
    "quantity": 2,
    "image": "https://cdn.tgdd.vn/Products/Images/42/251192/iphone-14-pro-den-1-1.jpg",
    "category": 2
  }, {
    "_id": 2,
    "name": "Tampflex",
    "price": 912,
    "quantity": 1,
    "image": "https://cdn.tgdd.vn/Products/Images/42/251192/iphone-14-pro-den-1-1.jpg",
    "category": 7
  }, {
    "_id": 17,
    "name": "Toughjoyfax",
    "price": 960,
    "quantity": 7,
    "image": "https://cdn.tgdd.vn/Products/Images/42/251192/iphone-14-pro-den-1-1.jpg",
    "category": 4
  }, {
    "_id": 3,
    "name": "Kanlam",
    "price": 944,
    "quantity": 7,
    "image": "https://cdn.tgdd.vn/Products/Images/42/251192/iphone-14-pro-den-1-1.jpg",
    "category": 7
  }, {
    "_id": 2,
    "name": "Tampflex",
    "price": 913,
    "quantity": 6,
    "image": "https://cdn.tgdd.vn/Products/Images/42/251192/iphone-14-pro-den-1-1.jpg",
    "category": 10
  }, {
    "_id": 13,
    "name": "Konklux",
    "price": 958,
    "quantity": 3,
    "image": "https://cdn.tgdd.vn/Products/Images/42/251192/iphone-14-pro-den-1-1.jpg",
    "category": 7
  }, {
    "_id": 18,
    "name": "Gembucket",
    "price": 550,
    "quantity": 3,
    "image": "https://cdn.tgdd.vn/Products/Images/42/251192/iphone-14-pro-den-1-1.jpg",
    "category": 3
  }, {
    "_id": 20,
    "name": "Veribet",
    "price": 878,
    "quantity": 9,
    "image": "https://cdn.tgdd.vn/Products/Images/42/251192/iphone-14-pro-den-1-1.jpg",
    "category": 9
  }, {
    "_id": 12,
    "name": "Sub-Ex",
    "price": 692,
    "quantity": 7,
    "image": "https://cdn.tgdd.vn/Products/Images/42/251192/iphone-14-pro-den-1-1.jpg",
    "category": 3
  }, {
    "_id": 15,
    "name": "Quo Lux",
    "price": 732,
    "quantity": 4,
    "image": "https://cdn.tgdd.vn/Products/Images/42/251192/iphone-14-pro-den-1-1.jpg",
    "category": 4
  }, {
    "_id": 5,
    "name": "Fix San",
    "price": 688,
    "quantity": 8,
    "image": "https://cdn.tgdd.vn/Products/Images/42/251192/iphone-14-pro-den-1-1.jpg",
    "category": 9
  }, {
    "_id": 19,
    "name": "Greenlam",
    "price": 834,
    "quantity": 6,
    "image": "https://cdn.tgdd.vn/Products/Images/42/251192/iphone-14-pro-den-1-1.jpg",
    "category": 7
  }, {
    "_id": 12,
    "name": "Keylex",
    "price": 510,
    "quantity": 7,
    "image": "https://cdn.tgdd.vn/Products/Images/42/251192/iphone-14-pro-den-1-1.jpg",
    "category": 4
  }, {
    "_id": 16,
    "name": "Bytecard",
    "price": 1000,
    "quantity": 4,
    "image": "https://cdn.tgdd.vn/Products/Images/42/251192/iphone-14-pro-den-1-1.jpg",
    "category": 6
  }, {
    "_id": 17,
    "name": "Cardify",
    "price": 551,
    "quantity": 9,
    "image": "https://cdn.tgdd.vn/Products/Images/42/251192/iphone-14-pro-den-1-1.jpg",
    "category": 7
  }, {
    "_id": 13,
    "name": "Subin",
    "price": 730,
    "quantity": 9,
    "image": "https://cdn.tgdd.vn/Products/Images/42/251192/iphone-14-pro-den-1-1.jpg",
    "category": 9
  }, {
    "_id": 17,
    "name": "Y-Solowarm",
    "price": 720,
    "quantity": 8,
    "image": "https://cdn.tgdd.vn/Products/Images/42/251192/iphone-14-pro-den-1-1.jpg",
    "category": 4
  }, {
    "_id": 1,
    "name": "Namfix",
    "price": 978,
    "quantity": 3,
    "image": "https://cdn.tgdd.vn/Products/Images/42/251192/iphone-14-pro-den-1-1.jpg",
    "category": 1
  }]